# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.ImageField(upload_to='documents/%Y/%m/%d')),
                ('Add_brand', models.CharField(blank=True, max_length=256)),
                ('Add_about', models.TextField(blank=True)),
                ('Add_entry_dt', models.DateTimeField(auto_now=True)),
                ('Add_views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
